### PR TITLE
Add curl to kali and parrot.

### PR DESCRIPTION
**Pull request by UsakoSenpai**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
is it only missing from kali?

**Comment by UsakoSenpai** [comment]
Uncertain, I noticed it on kali during the ctf. I was going to build the containers and check the other ones, but haven't yet. If you want to leave this open until then, I'll make an update (if needed) or I can make a PR later with changes (if any needed). Up to you. I'll try to look tonight, weekend at latest.

**Comment by ZeroChaos-** [comment]
you don't have to build the containers to test, just "docker exec -it rfhs/parrot /bin/bash" for example

**Comment by UsakoSenpai** [comment]
lol.. I know how containers work.. I just didn't know if they were available to pull (hadn't seen in a registry yet), but also I'd prefer to build just to make sure the Dockerfile changes work (although I did just pop this one in without doing so) 😅

**Comment by UsakoSenpai** [comment]
Sweet, I do see now they're all up on dockerhub. cool cool cool
https://hub.docker.com/search?q=rfhs&type=image

**Comment by ZeroChaos-** [comment]
> lol.. I know how containers work.. I just didn't know if they were available to pull (hadn't seen in a registry yet), but also I'd prefer to build just to make sure the Dockerfile changes work (although I did just pop this one in without doing so)

the public build scripts and the public startup scripts (both in this repo) kinda provide this hint ;-)

**Comment by UsakoSenpai** [comment]
Yeah, but you have to have looked at them to see that. lol I knew I needed to add curl and wanted to put that in before I forgot about it. So, I really only looked at the Dockerfile in that instant. 

I also had a couple other tools I installed, but uncertain they should be preinstalled. At least one had an existing alternative that I just didn't notice during the CTF, but saw in the Dockerfile. `hostapd` The other was `isc-dhcp-client`, which I couldn't find an alt for, but might just not know what the alt is. Not being certain about that, I left both out of the PR.

**Comment by ZeroChaos-** [comment]
hostapd-wpe isn't sufficient for some reason?

**Comment by UsakoSenpai** [comment]
> At least one had an existing alternative that I just didn't notice during the CTF, but saw in the Dockerfile. 

I'm assuming it is, which is why I didn't add `hostapd` in the PR. Probably, I somehow missed it / didn't know -wpe was a thing. owo; Looking at the project for that, I see now why it's preferred for this. :D

**Comment by UsakoSenpai** [comment]
@ZeroChaos- Added to parrot. The other two already have it.

**Comment by ZeroChaos-** [comment]
Thanks!

**Pull request merged**
